version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:
    jobs:
      - build-and-test


jobs:
  build-and-test:    
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install twine && twine upload
            
