jobs:
  build:
    executor: python/default
    steps:
      - checkout      
      - run:
          command: |
            pytest --version
          name: Test
orbs:
  python: circleci/python@1.1.0
version: 2.1
workflows:
  main:
    jobs:
      - build